service: bedrock-api-v1
provider:
  name: aws
  runtime: python3.12  # Specify the Python runtime version you are using
  region: us-east-1
  memorySize: 1024     # Choose your preferred region
  deploymentBucket:
    name: bedrock-python-code  # Specify your S3 bucket name for deployment
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   timeout: 30
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
package:
  exclude:
    - node_modules/**
    - tests/**
    - .git/**
    - README.md